import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  GetStaticProps,
  GetStaticPaths,
  GetServerSideProps,
  NextPage,
  InferGetServerSidePropsType,
} from "next";

const inter = Inter({ subsets: ["latin"] });

type Data = {
  friends: Record<string, string>[];
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  let friends;

  try {
    const response = await fetch(
      process.env.NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT as string,
      {
        method: "POST",
        headers: {
          "x-hasura-admin-secret": process.env.HASURA_ADMIN_SECRET as string,
        },
        body: JSON.stringify({
          query: `query {
            friend {
              name
            }
          }`,
        }),
      }
    );

    const result = await response.json();
    const data = result.data;

    friends = data.friend;

    console.log(result);
  } catch (e) {}

  return {
    props: { friends },
  };
};

const Home: NextPage = ({
  friends,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {friends.map((hoge: any, index: number) => (
          <p key={index}>{hoge.name}</p>
        ))}
      </main>
    </div>
  );
};

export default Home;
